CREATE TABLE [dbo].[PurchaseTable]
(
	[Purchase_ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[Cart_ID] INT NOT NULL FOREIGN KEY REFERENCES CartTable([Cart_ID]) ON DELETE CASCADE,
	[Product_ID] INT NOT NULL FOREIGN KEY REFERENCES ProductTable([Product_ID]) ON DELETE CASCADE,
	[Quantity] INT NOT NULL
)
